title: "The Flow"
theme: tract
copyright: Lei Ma

taxonomies:
  tag: tags


params:
  description: Notes for data scientists in the logistics industry.
  icon_set: ionicons
  colors:
    primary: '#277e98'
    secondary: '#1e88e5'
  fonts:
    - name: Alata
      sizes:
        - 400
      type: sans_serif
    - name: Roboto Mono
      sizes:
        - 400
      type: monospace
  social:
    linkedin:
      id: leima137
    github:
      repo: emptymalei/theflow


menu:
  main:
    - name: Road Freight
      identifier: rf
      url: /road-freight
      weight: 1
    - name: Road Freight Basics
      parent: rf
      url: /road-freight/basics
    - name: Economics
      identifier: econ
      url: /economics
      weight: 2
    - name: Auction Theory
      parent: econ
      url: /economics/auction-theory-basics



markup:
  highlight:
    style: dracula

outputs:
  home:
    - HTML
    - JSON
